[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
riscv = "0.7"

[dependencies.fdt-rs]
version = "0.4"
default-features = false

[dependencies.indenter]
version = "0.3"
default-features = false

[build-dependencies]
cc = "1.0.72"
