[target.riscv64gc-unknown-none-elf]
runner = "qemu-system-riscv64 -nographic -machine virt -m 1G -smp 4 -serial mon:stdio -d int -D log.txt -bios ../opensbi/build/platform/generic/firmware/fw_jump.elf -kernel"
rustflags = [
  "-C", "link-arg=-Tlinker.ld",
  "-C", "link-arg=-nostartfiles",
  "-C", "force-frame-pointers=yes",
]
linker = "riscv64-unknown-elf-gcc"

[build]
target = "riscv64gc-unknown-none-elf"

[env]
HOST_CC="gcc-12"
TARGET_CC = "riscv64-unknown-elf-gcc"
